Esherymack/CS320-Team-Fractal-Website

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/LogInController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/LogIn.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/CreateAccountServlet.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/LogInServlet.java, CS320_Team_Fractal_Website/war/WEB-INF/web.xml, CS320_Team_Fractal_Website/war/_view/createAccount.jsp, CS320_Team_Fractal_Website/war/_view/logIn.jsp
I worked on log in and create account pages, while adding create account jsp and servlet.
=> Log in page

CS320_Team_Fractal_Website/main/edu/ycp/cs320/CS320_Team_Fractal_Website/main/Main.java, CS320_Team_Fractal_Website/war/_view/landingPage.jsp
Added proper links on landing page
=> Zac branch

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java
=> Adjusted main page servlet to use fractal abstraction

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/LogInTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/CreateAccountServlet.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/LogInServlet.java, CS320_Team_Fractal_Website/war/_view/createAccount.jsp, CS320_Team_Fractal_Website/war/_view/logIn.jsp
=> Improved log in and account creation pages adding data validation and page links

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/FractalController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/MandelbrotController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/SierpinskiController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Sierpinski.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/_view/mainPage.jsp
The selection of fractals is now more streamlined and easier to use. Only the relevant inputs and labels are shown, and adding a new fractal type is much simpler
=> Fractal abstraction

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/LogInTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/_view/landingPage.jsp, CS320_Team_Fractal_Website/war/_view/logIn.jsp, CS320_Team_Fractal_Website/war/_view/mainPage.jsp, CS320_Team_Fractal_Website/war/c.css
Implemented various fractal information and added account links for main page and log in page.
=> Implemented fractal info and added account page links

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/LogInControllerTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/user/LogInController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/CreateAccountServlet.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/LogInServlet.java
Adjusted the InitDatabase.init() placement, database accessing, and controllers to use the same way of making the code that Hake used.
=> Persistence

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/account/GalleryTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/BrowseFractalsControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/databse/DerbyDatabaseTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/FractalTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/FractalController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/MandelbrotController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/SierpinskiController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/pages/BrowseFractalsController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/DerbyDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/IDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Fractal.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Mandelbrot.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Sierpinski.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/BrowseFractalsServlet.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/WEB-INF/web.xml, CS320_Team_Fractal_Website/war/_view/browseFractals.jsp, CS320_Team_Fractal_Website/war/_view/landingPage.jsp, CS320_Team_Fractal_Website/war/_view/mainPage.jsp
Fractals can be saved from the main page and viewed from the new viewFractals page.
Make sure to delete your old test.db folder and run the main in DerbyDatabase again.
=> Save fractals

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/DerbyDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Fractal.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/_view/mainPage.jsp
To add a fractal, 4 files must be changed
1. the new fractal subclass of the Fractal super class
2. the new fractal controller subclass of the FractalController super class
3. the new Fractal super class, the method that creates an appropriate model object 
4. the MainPage jsp for selecting which parameters should show up, and the labels of those parameters, specifically the script that is called when the drop down menu is selected
=> Abstracted away more fractal concepts, much more practical to add fractals

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/_view/mainPage.jsp, CS320_Team_Fractal_Website/war/c.css
Images can now be downloaded from the main page
=> Download images

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/BarnsleyControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/FractalControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/KochControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/MandelbrotControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/SierpinskiControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/BarnsleyTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/FractalTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/KochTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/MandelbrotTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/SierpinskiTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/BarnsleyController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/FractalController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/KochController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/MandelbrotController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/SierpinskiController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Barnsley.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Fractal.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Koch.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Mandelbrot.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Sierpinski.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/_view/mainPage.jsp, CS320_Team_Fractal_Website/war/c.css
This merge adds the Barnsley fern and main page enhancement branches and resolves merge conflicts and errors in the files.
=> Fractal enhancement

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/pages/BrowseFractalsController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/DerbyDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/IDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/BrowseFractalsServlet.java, CS320_Team_Fractal_Website/war/_view/browseFractals.jsp
Fixes the SQL query to search for fractals by name, either full or partial
=> Fixed wonky SQL query

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/pages/BrowseFractalsController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/DerbyDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/database/IDatabase.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/BrowseFractalsServlet.java, CS320_Team_Fractal_Website/war/_view/browseFractals.jsp
There is an issue with get the right gradient type, unsure of issue browse fractals is now set up to get fractals by gradient type. Right now they are all showing up as none.
=> I added buttons and query for the gradient type in browse fractals.

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/BrowseFractalsServlet.java, CS320_Team_Fractal_Website/war/_view/browseFractals.jsp, CS320_Team_Fractal_Website/war/_view/viewAccount.jsp, CS320_Team_Fractal_Website/war/c.css
There is now a lightbox present on both the browseFractals and viewAccount pages. There is also a dropdown menu on browseFractals for filtering by fractal type.
=> Lightbox and Dropdown CSS

CS320_Team_Fractal_Website/.classpath, CS320_Team_Fractal_Website/war/_view/mainPage.jsp, CS320_Team_Fractal_Website/war/c.css
The display is a preview for what each color will look like
=> Replaced text box inputs for colors with sliders and added color display

CS320_Team_Fractal_Website/.classpath, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/ViewAccountServlet.java, CS320_Team_Fractal_Website/war/_view/viewAccount.jsp, CS320_Team_Fractal_Website/war/c.css, scrypt/.project
Added table to improve layout of page. Can now download fractals. Fractal information is separated from the render button.
=> View account

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/BurningShipControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/TricornControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/BurningShipTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/TricornTest.java
Test cases for tricorn and burning ship
=> added test cases for fractals

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/FractalTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Barnsley.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/BurningShip.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Fractal.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Hexaflake.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Julia.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Koch.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Mandelbrot.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Sierpinski.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Tricorn.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/BrowseFractalsServlet.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/MainPageServlet.java, CS320_Team_Fractal_Website/war/_view/mainPage.jsp
Fractals now are removed from the browse list correctly after an admin deletes them. Fractals now have an abstract method for if they use location or not.
=> Small changes

CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/HexaflakeControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/ViewAccountControllerTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/BarnsleyTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/BurningShipTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/HexaflakeTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/JuliaTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/KochTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/MandelbrotTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/SierpinskiTest.java, CS320_Team_Fractal_Website/junit/edu/ycp/cs320/CS320_Team_Fractal_Website/model/TricornTest.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/fractal/HexaflakeController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/controller/user/LogInController.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Fractal.java, CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/model/fractal/Hexaflake.java
Also fixed some other fractal test cases
=> Added Hexflake fractal and associated test cases

CS320_Team_Fractal_Website/src/edu/ycp/cs320/CS320_Team_Fractal_Website/servlet/BrowseFractalsServlet.java
=> Fixed bug where an evely divisible number of fractals had an extra page
